using Asp.Versioning;
using FitSpec.Core.DTOs;
using FitSpec.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitSpec.API.Controllers;

[ApiController]
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/builds")]
public class BuildExportController : ControllerBase
{
    private readonly IProductRepository _productRepository;

    public BuildExportController(IProductRepository productRepository)
    {
        _productRepository = productRepository;
    }

    [HttpPost("export-pdf")]
    public async Task<IActionResult> ExportPdf([FromBody] BuildExportRequest request)
    {
        if (request.Items.Count == 0)
            return BadRequest(ApiResponse<string>.Fail("No items in build."));

        var productIds = request.Items.Select(i => i.ProductId).ToArray();
        var products = await _productRepository.GetProductsByIdsAsync(productIds);

        // Build HTML for PDF conversion
        var totalPrice = 0m;
        var rowsHtml = "";
        var itemNum = 0;
        foreach (var item in request.Items)
        {
            var product = products.FirstOrDefault(p => p.Id == item.ProductId);
            if (product == null) continue;
            itemNum++;
            var lineTotal = product.Price * item.Quantity;
            totalPrice += lineTotal;
            rowsHtml += $@"<tr>
                <td style='padding:8px;border-bottom:1px solid #eee'>{itemNum}</td>
                <td style='padding:8px;border-bottom:1px solid #eee'>{product.Name}</td>
                <td style='padding:8px;border-bottom:1px solid #eee'>{product.Brand}</td>
                <td style='padding:8px;border-bottom:1px solid #eee'>{product.SKU}</td>
                <td style='padding:8px;border-bottom:1px solid #eee'>{product.CategoryName}</td>
                <td style='padding:8px;border-bottom:1px solid #eee;text-align:right'>{item.Quantity}</td>
                <td style='padding:8px;border-bottom:1px solid #eee;text-align:right'>${product.Price:F2}</td>
                <td style='padding:8px;border-bottom:1px solid #eee;text-align:right'>${lineTotal:F2}</td>
            </tr>";
        }

        var vehicleInfo = request.VehicleName ?? "No vehicle selected";
        var date = DateTime.UtcNow.ToString("MMMM dd, yyyy");

        var html = $@"<!DOCTYPE html>
<html>
<head><meta charset='utf-8'><title>FitSpec Build Sheet</title></head>
<body style='font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;color:#333'>
  <div style='display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #1a237e;padding-bottom:16px;margin-bottom:24px'>
    <div>
      <h1 style='margin:0;color:#1a237e;font-size:28px'>FitSpec</h1>
      <p style='margin:4px 0 0;color:#666;font-size:14px'>Vehicle Parts Build Sheet</p>
    </div>
    <div style='text-align:right'>
      <p style='margin:0;font-size:14px;color:#666'>{date}</p>
    </div>
  </div>
  <div style='background:#f5f7fa;border-radius:8px;padding:16px;margin-bottom:24px'>
    <h3 style='margin:0 0 4px;color:#1a237e'>Vehicle</h3>
    <p style='margin:0;font-size:16px'>{vehicleInfo}</p>
  </div>
  <table style='width:100%;border-collapse:collapse;font-size:14px'>
    <thead>
      <tr style='background:#1a237e;color:white'>
        <th style='padding:10px 8px;text-align:left'>#</th>
        <th style='padding:10px 8px;text-align:left'>Product</th>
        <th style='padding:10px 8px;text-align:left'>Brand</th>
        <th style='padding:10px 8px;text-align:left'>SKU</th>
        <th style='padding:10px 8px;text-align:left'>Category</th>
        <th style='padding:10px 8px;text-align:right'>Qty</th>
        <th style='padding:10px 8px;text-align:right'>Unit Price</th>
        <th style='padding:10px 8px;text-align:right'>Total</th>
      </tr>
    </thead>
    <tbody>{rowsHtml}</tbody>
    <tfoot>
      <tr style='font-weight:bold;border-top:2px solid #1a237e'>
        <td colspan='7' style='padding:12px 8px;text-align:right'>Total:</td>
        <td style='padding:12px 8px;text-align:right;color:#1a237e;font-size:16px'>${totalPrice:F2}</td>
      </tr>
    </tfoot>
  </table>
  <div style='margin-top:32px;padding-top:16px;border-top:1px solid #ddd;color:#888;font-size:12px;text-align:center'>
    <p>Generated by FitSpec — Vehicle Parts Fitment Finder</p>
  </div>
</body>
</html>";

        // Return HTML that can be printed as PDF client-side
        return Content(html, "text/html");
    }
}
